find_path(TINYXML2_INCLUDE_DIR Audio.hpp
  HINTS
    ENV TINYXML2DIR
  PATH_SUFFIXES SFML
                # path suffixes to search inside ENV{SDLDIR}
                include include
)

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(VC_LIB_PATH_SUFFIX lib/x64)
else()
  set(VC_LIB_PATH_SUFFIX lib/x86)
endif()

find_library(TINYXML2_LIBRARY
  NAMES tinyxml2
  HINTS
    ENV TINYXML2DIR
  PATH_SUFFIXES lib ${VC_LIB_PATH_SUFFIX}
)

if(TINYXML2DIR AND EXISTS "${TINYXML2DIR}/tinyxml2.h")
    file(STRINGS "${TINYXML2DIR}/tinyxml2.h" TINYXML2_MAJOR_VERSION_LINE REGEX "^#define[ \t]+TINYXML2_MAJOR_VERSION[ \t]+[0-9]+$")
    file(STRINGS "${TINYXML2DIR}/tinyxml2.h" TINYXML2_MINOR_VERSION_LINE REGEX "^#define[ \t]+TINYXML2_MINOR_VERSION[ \t]+[0-9]+$")
    file(STRINGS "${TINYXML2DIR}/tinyxml2.h" TINYXML2_PATCH_VERSION_LINE REGEX "^#define[ \t]+TINYXML2_PATCH_VERSION[ \t]+[0-9]+$")
    
    string(REGEX REPLACE "^#define[ \t]+TINYXML2_MAJOR_VERSION[ \t]+([0-9]+)$" "\\1" TINYXML2_MAJOR_VERSION "${TINYXML2_MAJOR_VERSION_LINE}")
    string(REGEX REPLACE "^#define[ \t]+TINYXML2_MINOR_VERSION[ \t]+([0-9]+)$" "\\1" TINYXML2_MINOR_VERSION "${TINYXML2_MINOR_VERSION_LINE}")
    string(REGEX REPLACE "^#define[ \t]+TINYXML2_PATCH_VERSION[ \t]+([0-9]+)$" "\\1" TINYXML2_PATCH_VERSION "${TINYXML2_PATCH_VERSION_LINE}")

    set(TINYXML2_VERSION_STRING ${TINYXML2_MAJOR_VERSION}.${TINYXML2_MINOR_VERSION}.${TINYXML2_PATCH_VERSION})
    unset(TINYXML2_MAJOR_VERSION_LINE)
    unset(TINYXML2_MINOR_VERSION_LINE)
    unset(TINYXML2_PATCH_VERSION_LINE)
    unset(TINYXML2_MAJOR_VERSION)
    unset(TINYXML2_MINOR_VERSION)
    unset(TINYXML2_PATCH_VERSION)
endif()

set(TINYXML2_LIBRARIES ${TINYXML2_LIBRARY})
set(TINYXML2_INCLUDE_DIRS ${TINYXML2_INCLUDE_DIR})
include(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(tinyxml2
                                REQUIRED_VARS TINYXML2_LIBRARIES TINYXML2_INCLUDE_DIRS
                                VERSION_VAR TINYXML2_VERSION_STRING)
mark_as_advanced(TINYXML2_LIBRARY TINYXML2_INCLUDE_DIR)
